# Generated by Django 5.1.5 on 2025-05-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
