# Generated by Django 5.1.5 on 2025-05-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_delete_gamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='totalScore',
            field=models.IntegerField(default=0),
        ),
    ]
