# Generated by Django 4.2.19 on 2025-03-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameresult',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='correct_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='difficulty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='player_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='total_attempts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='wrong_count',
            field=models.IntegerField(),
        ),
    ]
