# Generated by Django 5.1.7 on 2025-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('screen', models.CharField(max_length=100)),
                ('player', models.CharField(max_length=100)),
                ('trial_number', models.IntegerField(blank=True, null=True)),
                ('voice_text', models.TextField(blank=True, null=True)),
                ('button_clicked', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('total_trials', models.IntegerField(default=0)),
                ('correct_trials', models.IntegerField(default=0)),
                ('incorrect_trials', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
