# Generated by Django 5.1.7 on 2025-04-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page', models.CharField(max_length=100)),
                ('player', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.TextField()),
            ],
        ),
    ]
